import { randomUUID } from "node:crypto";
import {
  addDays,
  assessFood,
  eligibleRecipes,
  generateMealPlan,
  libraryRecipe,
  mealAlternatives,
  NUTRITION_LIMITS,
  PLAN_LIMITS,
  PlanGenerationError,
  portionNutrients,
  presentMacros,
  RECIPE_LIBRARY,
  recipeAsFood,
  SERVING_STEPS,
  sumNutrients,
  type LibraryRecipe,
  type MealSlot,
  type PersonalizationProfile,
  type PlanTargets,
} from "@form/domain";
import type { Db } from "../../db";
import { transaction } from "../../db";
import { HttpError } from "../../http/errors";
import type { AppContext } from "../../shared/context";
import type { UserClock } from "../../shared/userClock";
import { deleteLog, insertRecipeLog, logExists } from "../nutrition/service";
import { targetOn } from "../nutrition/targets";
import { userState } from "../users/service";
import { syncPlanGroceries } from "./grocery";

/**
 * Recipes and meal plans. Plans are generated by the domain MealPlanGenerator from FORM's recipe
 * library, the user's targets and personalization; every edit keeps the same hard rules (only
 * recipes safe for the user). A planned meal becomes food only when the user marks it eaten.
 */

// ---- Recipes -----------------------------------------------------------------------------------

function personalization(db: Db, userId: string, today: string): PersonalizationProfile {
  return userState(db, userId, today).personalization;
}

function fitOf(recipe: LibraryRecipe, p: PersonalizationProfile) {
  const a = assessFood(recipeAsFood(recipe), p);
  const soft = eligibleRecipes([recipe], p)[0];
  return { verdict: a.verdict, matchedAllergens: a.matchedAllergens, disliked: a.disliked, overTime: soft?.overTime ?? false, overBudget: soft?.overBudget ?? false };
}

function savedIds(db: Db, userId: string): Set<string> {
  return new Set((db.prepare("SELECT recipe_id FROM saved_recipes WHERE user_id = ?").all(userId) as { recipe_id: string }[]).map((r) => r.recipe_id));
}

export function recipeView(r: LibraryRecipe, p: PersonalizationProfile, saved: boolean) {
  return {
    id: r.id,
    title: r.title,
    slots: r.slots,
    servings: r.servings,
    prepMinutes: r.prepMinutes,
    cookMinutes: r.cookMinutes,
    totalMinutes: r.totalMinutes,
    perServing: r.perServingDisplay,
    servingGrams: Math.round(r.servingGrams),
    ingredients: r.ingredients.map((i) => ({ foodId: i.foodId, name: i.name, amount: i.amount, unit: i.unit, note: i.note, aisle: i.aisle })),
    pantry: r.pantry,
    steps: r.steps,
    allergens: r.allergens,
    suitableFor: r.suitableFor,
    styles: r.styles,
    costTier: r.costTier,
    source: r.source,
    saved,
    fit: fitOf(r, p),
  };
}

/** Recipes the user can be offered: never anything their allergies or restrictions exclude. */
export function listRecipes(db: Db, userId: string, today: string, filter: { slot?: MealSlot; q?: string; saved?: boolean }) {
  const p = personalization(db, userId, today);
  const saved = savedIds(db, userId);
  const q = filter.q?.trim().toLowerCase();
  return eligibleRecipes(RECIPE_LIBRARY, p)
    .filter((f) => !filter.slot || f.recipe.slots.includes(filter.slot))
    .filter((f) => !filter.saved || saved.has(f.recipe.id))
    .filter((f) => !q || f.recipe.title.toLowerCase().includes(q) || f.recipe.ingredients.some((i) => i.name.toLowerCase().includes(q)))
    .sort((a, b) => Number(a.disliked) - Number(b.disliked) || a.recipe.title.localeCompare(b.recipe.title))
    .map((f) => recipeView(f.recipe, p, saved.has(f.recipe.id)));
}

export function getRecipe(db: Db, userId: string, today: string, id: string) {
  const r = libraryRecipe(id);
  if (!r) throw new HttpError(404, "not_found", "Recipe not found");
  return recipeView(r, personalization(db, userId, today), savedIds(db, userId).has(id));
}

export function saveRecipe(ctx: AppContext, userId: string, id: string, save: boolean) {
  if (!libraryRecipe(id)) throw new HttpError(404, "not_found", "Recipe not found");
  if (save) ctx.db.prepare("INSERT INTO saved_recipes (user_id, recipe_id, saved_at) VALUES (?, ?, ?) ON CONFLICT DO NOTHING").run(userId, id, ctx.now().toISOString());
  else ctx.db.prepare("DELETE FROM saved_recipes WHERE user_id = ? AND recipe_id = ?").run(userId, id);
}

// ---- Plans -------------------------------------------------------------------------------------

interface PlanRow {
  id: string;
  user_id: string;
  client_plan_id: string;
  start_date: string;
  days: number;
  status: "active" | "archived";
  targets: string;
  warnings: string;
  created_at: string;
  updated_at: string;
}

interface MealRow {
  id: string;
  plan_id: string;
  user_id: string;
  local_date: string;
  slot: MealSlot;
  recipe_id: string;
  servings: number;
  position: number;
  food_log_id: string | null;
  eaten_at: string | null;
  created_at: string;
  updated_at: string;
}

const planDates = (p: Pick<PlanRow, "start_date" | "days">) => Array.from({ length: p.days }, (_, i) => addDays(p.start_date, i));

function ownPlan(db: Db, userId: string, id: string): PlanRow {
  const row = db.prepare("SELECT * FROM meal_plans WHERE id = ? AND user_id = ?").get(id, userId) as PlanRow | undefined;
  if (!row) throw new HttpError(404, "not_found", "Meal plan not found");
  return row;
}

function ownMeal(db: Db, userId: string, planId: string, mealId: string): MealRow {
  const row = db.prepare("SELECT * FROM planned_meals WHERE id = ? AND plan_id = ? AND user_id = ?").get(mealId, planId, userId) as MealRow | undefined;
  if (!row) throw new HttpError(404, "not_found", "Meal not found");
  return row;
}

function mealRows(db: Db, planId: string): MealRow[] {
  return db.prepare("SELECT * FROM planned_meals WHERE plan_id = ? ORDER BY local_date, CASE slot WHEN 'breakfast' THEN 0 WHEN 'lunch' THEN 1 WHEN 'dinner' THEN 2 ELSE 3 END, position").all(planId) as unknown as MealRow[];
}

/** Eaten only while its food log exists — deleting the entry from Eat makes it planned again. */
function isEaten(db: Db, userId: string, m: MealRow): boolean {
  return m.food_log_id !== null && logExists(db, userId, m.food_log_id);
}

function mealView(db: Db, userId: string, m: MealRow, today: string) {
  const r = libraryRecipe(m.recipe_id);
  const n = r ? portionNutrients(r, m.servings) : { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0 };
  const eaten = isEaten(db, userId, m);
  return {
    id: m.id,
    date: m.local_date,
    slot: m.slot,
    recipeId: m.recipe_id,
    title: r?.title ?? "Recipe no longer available",
    totalMinutes: r?.totalMinutes ?? null,
    servings: m.servings,
    nutrients: presentMacros(n),
    status: eaten ? ("eaten" as const) : ("planned" as const),
    foodLogId: eaten ? m.food_log_id : null,
    /** Food can be logged for today or up to 7 days back — never ahead of time. */
    canMarkEaten: !eaten && m.local_date <= today && m.local_date >= addDays(today, -NUTRITION_LIMITS.maxBackdateDays),
    _exact: n,
    _eaten: eaten,
  };
}

export function planView(db: Db, userId: string, p: PlanRow, today: string) {
  const meals = mealRows(db, p.id).map((m) => mealView(db, userId, m, today));
  const dates = planDates(p);
  const byDate = Object.fromEntries(
    dates.map((d) => {
      const day = meals.filter((m) => m.date === d);
      return [d, { planned: presentMacros(sumNutrients(day.map((m) => m._exact))), eaten: presentMacros(sumNutrients(day.filter((m) => m._eaten).map((m) => m._exact))), meals: day.length }];
    }),
  );
  return {
    id: p.id,
    clientPlanId: p.client_plan_id,
    startDate: p.start_date,
    days: p.days,
    dates,
    status: p.status,
    targets: JSON.parse(p.targets) as PlanTargets,
    warnings: JSON.parse(p.warnings) as string[],
    meals: meals.map(({ _exact, _eaten, ...m }) => m),
    totalsByDate: byDate,
    createdAt: p.created_at,
    updatedAt: p.updated_at,
  };
}

function touch(ctx: AppContext, planId: string) {
  ctx.db.prepare("UPDATE meal_plans SET updated_at = ? WHERE id = ?").run(ctx.now().toISOString(), planId);
}

function insertMeal(ctx: AppContext, userId: string, planId: string, m: { date: string; slot: MealSlot; recipeId: string; servings: number }, position: number) {
  const now = ctx.now().toISOString();
  const id = randomUUID();
  ctx.db
    .prepare("INSERT INTO planned_meals (id, plan_id, user_id, local_date, slot, recipe_id, servings, position, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
    .run(id, planId, userId, m.date, m.slot, m.recipeId, m.servings, position, now, now);
  return id;
}

export interface CreatePlanInput {
  clientPlanId: string;
  startDate?: string;
  days: 1 | 7;
  /** Advanced planning: saved recipes win close calls. */
  preferSaved?: boolean;
}

/**
 * Generates a plan from the user's targets and personalization. Idempotent on `clientPlanId`. A
 * new plan replaces (archives) any active plan it overlaps; logged food is never touched.
 */
export function createPlan(ctx: AppContext, userId: string, input: CreatePlanInput, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    const existing = db.prepare("SELECT * FROM meal_plans WHERE user_id = ? AND client_plan_id = ?").get(userId, input.clientPlanId) as PlanRow | undefined;
    if (existing) return { created: false, plan: planView(db, userId, existing, clock.today) };

    const start = input.startDate ?? clock.today;
    if (start < clock.today || start > addDays(clock.today, 14)) throw new HttpError(422, "date_out_of_range", "Plans can start today or up to two weeks ahead");
    const t = targetOn(db, userId, start) ?? targetOn(db, userId, clock.today);
    if (!t) throw new HttpError(422, "targets_required", "Add your body details in Profile first, so the plan fits your energy needs safely.");
    const targets: PlanTargets = { kcal: t.targetKcal, proteinG: t.proteinG, carbsG: t.carbsG, fatG: t.fatG, safeFloorKcal: t.safeFloorKcal };
    const dates = Array.from({ length: input.days }, (_, i) => addDays(start, i));
    let generated;
    try {
      generated = generateMealPlan({
        dates,
        targets,
        personalization: personalization(db, userId, clock.today),
        recipes: RECIPE_LIBRARY,
        seed: `${userId}|${start}|${input.clientPlanId}`,
        favorites: input.preferSaved ? savedIds(db, userId) : undefined,
      });
    } catch (e) {
      if (e instanceof PlanGenerationError) throw new HttpError(422, e.code, e.message);
      throw e;
    }

    const end = addDays(start, input.days - 1);
    const overlapping = (db.prepare("SELECT * FROM meal_plans WHERE user_id = ? AND status = 'active'").all(userId) as unknown as PlanRow[]).filter(
      (p) => p.start_date <= end && addDays(p.start_date, p.days - 1) >= start,
    );
    const now = ctx.now().toISOString();
    for (const p of overlapping) db.prepare("UPDATE meal_plans SET status = 'archived', updated_at = ? WHERE id = ?").run(now, p.id);

    const id = randomUUID();
    db.prepare("INSERT INTO meal_plans (id, user_id, client_plan_id, start_date, days, status, targets, warnings, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'active', ?, ?, ?, ?)").run(
      id,
      userId,
      input.clientPlanId,
      start,
      input.days,
      JSON.stringify(targets),
      JSON.stringify(generated.warnings),
      now,
      now,
    );
    for (const day of generated.days) day.meals.forEach((m, i) => insertMeal(ctx, userId, id, m, i));
    syncPlanGroceries(ctx, userId, clock);
    return { created: true, plan: planView(db, userId, ownPlan(db, userId, id), clock.today) };
  });
}

/** The active plan covering today, or the next one starting soon. */
export function currentPlan(ctx: AppContext, userId: string, clock: UserClock) {
  const rows = (ctx.db.prepare("SELECT * FROM meal_plans WHERE user_id = ? AND status = 'active' ORDER BY start_date, created_at DESC").all(userId) as unknown as PlanRow[]).filter(
    (p) => addDays(p.start_date, p.days - 1) >= clock.today,
  );
  const covering = rows.find((p) => p.start_date <= clock.today) ?? rows[0];
  return covering ? planView(ctx.db, userId, covering, clock.today) : null;
}

export function getPlan(ctx: AppContext, userId: string, id: string, clock: UserClock) {
  return planView(ctx.db, userId, ownPlan(ctx.db, userId, id), clock.today);
}

export function deletePlan(ctx: AppContext, userId: string, id: string, clock: UserClock) {
  transaction(ctx.db, () => {
    ownPlan(ctx.db, userId, id);
    // Planned meals go; anything already logged as eaten stays in the food log.
    ctx.db.prepare("DELETE FROM meal_plans WHERE id = ? AND user_id = ?").run(id, userId);
    syncPlanGroceries(ctx, userId, clock);
  });
}

function suitableRecipe(db: Db, userId: string, today: string, recipeId: string): LibraryRecipe {
  const r = libraryRecipe(recipeId);
  if (!r) throw new HttpError(404, "recipe_not_found", "Recipe not found");
  if (eligibleRecipes([r], personalization(db, userId, today)).length === 0) {
    throw new HttpError(422, "recipe_not_suitable", "That recipe conflicts with your allergies or diet restrictions");
  }
  return r;
}

function validServings(s: number): number {
  if (!(SERVING_STEPS as readonly number[]).includes(s)) throw new HttpError(422, "invalid_servings", `Choose ${SERVING_STEPS.join(", ")} servings`);
  return s;
}

export function updateMeal(ctx: AppContext, userId: string, planId: string, mealId: string, patch: { servings?: number; recipeId?: string }, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    ownPlan(db, userId, planId);
    const m = ownMeal(db, userId, planId, mealId);
    if (isEaten(db, userId, m)) throw new HttpError(409, "meal_eaten", "This meal is already logged as eaten — unmark it first to change it");
    const recipeId = patch.recipeId ?? m.recipe_id;
    if (patch.recipeId) suitableRecipe(db, userId, clock.today, patch.recipeId);
    const servings = patch.servings !== undefined ? validServings(patch.servings) : m.servings;
    db.prepare("UPDATE planned_meals SET recipe_id = ?, servings = ?, food_log_id = NULL, eaten_at = NULL, updated_at = ? WHERE id = ?").run(recipeId, servings, ctx.now().toISOString(), m.id);
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

export function addMeal(ctx: AppContext, userId: string, planId: string, input: { date: string; slot: MealSlot; recipeId: string; servings: number }, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    const p = ownPlan(db, userId, planId);
    if (!planDates(p).includes(input.date)) throw new HttpError(422, "date_out_of_range", "That day isn't part of this plan");
    suitableRecipe(db, userId, clock.today, input.recipeId);
    validServings(input.servings);
    const count = (db.prepare("SELECT COUNT(*) AS n FROM planned_meals WHERE plan_id = ? AND local_date = ?").get(planId, input.date) as { n: number }).n;
    if (count >= PLAN_LIMITS.maxMealsPerDay) throw new HttpError(422, "too_many_meals", `A day can have at most ${PLAN_LIMITS.maxMealsPerDay} planned meals`);
    insertMeal(ctx, userId, planId, input, count);
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

export function removeMeal(ctx: AppContext, userId: string, planId: string, mealId: string, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    ownPlan(db, userId, planId);
    ownMeal(db, userId, planId, mealId);
    // Removing it from the plan doesn't un-eat it: a linked food log stays.
    db.prepare("DELETE FROM planned_meals WHERE id = ?").run(mealId);
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

/** Copies one day's meals onto other days of the plan (their meals not yet eaten are replaced). */
export function repeatDay(ctx: AppContext, userId: string, planId: string, fromDate: string, toDates: string[], clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    const p = ownPlan(db, userId, planId);
    const dates = planDates(p);
    if (!dates.includes(fromDate) || toDates.some((d) => !dates.includes(d) || d === fromDate)) throw new HttpError(422, "date_out_of_range", "Choose other days of this plan");
    const source = mealRows(db, planId).filter((m) => m.local_date === fromDate);
    if (source.length === 0) throw new HttpError(422, "nothing_to_repeat", "That day has no meals to repeat");
    for (const d of new Set(toDates)) {
      const target = mealRows(db, planId).filter((m) => m.local_date === d);
      for (const m of target) if (!isEaten(db, userId, m)) db.prepare("DELETE FROM planned_meals WHERE id = ?").run(m.id);
      const kept = target.filter((m) => isEaten(db, userId, m)).length;
      source.forEach((m, i) => insertMeal(ctx, userId, planId, { date: d, slot: m.slot, recipeId: m.recipe_id, servings: m.servings }, kept + i));
    }
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

/**
 * Marks a planned meal eaten: logs the planned portion as a recipe entry (estimated) on that day.
 * Idempotent: the same meal can only be logged once, and a retry returns the same entry.
 */
export function markEaten(ctx: AppContext, userId: string, planId: string, mealId: string, clientLogId: string, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    ownPlan(db, userId, planId);
    const m = ownMeal(db, userId, planId, mealId);
    if (isEaten(db, userId, m)) return getPlan(ctx, userId, planId, clock);
    if (m.local_date > clock.today) throw new HttpError(422, "not_yet", "You can mark a meal eaten on the day you eat it");
    const r = libraryRecipe(m.recipe_id);
    if (!r) throw new HttpError(422, "recipe_unavailable", "This recipe is no longer available — log the food another way");
    const log = insertRecipeLog(ctx, userId, { clientLogId, localDate: m.local_date, mealType: m.slot, title: r.title, servings: m.servings, servingGrams: r.servingGrams, perServing: r.perServing }, clock);
    db.prepare("UPDATE planned_meals SET food_log_id = ?, eaten_at = ?, updated_at = ? WHERE id = ?").run(log.id, ctx.now().toISOString(), ctx.now().toISOString(), m.id);
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

/** Un-marks a meal: its food log is removed and it's planned again. */
export function unmarkEaten(ctx: AppContext, userId: string, planId: string, mealId: string, clock: UserClock) {
  const { db } = ctx;
  return transaction(db, () => {
    ownPlan(db, userId, planId);
    const m = ownMeal(db, userId, planId, mealId);
    if (m.food_log_id && logExists(db, userId, m.food_log_id)) deleteLog(ctx, userId, m.food_log_id);
    db.prepare("UPDATE planned_meals SET food_log_id = NULL, eaten_at = NULL, updated_at = ? WHERE id = ?").run(ctx.now().toISOString(), m.id);
    touch(ctx, planId);
    syncPlanGroceries(ctx, userId, clock);
    return getPlan(ctx, userId, planId, clock);
  });
}

export function alternatives(ctx: AppContext, userId: string, planId: string, mealId: string, clock: UserClock) {
  ownPlan(ctx.db, userId, planId);
  const m = ownMeal(ctx.db, userId, planId, mealId);
  return mealAlternatives({ current: { recipeId: m.recipe_id, servings: m.servings, slot: m.slot }, recipes: RECIPE_LIBRARY, personalization: personalization(ctx.db, userId, clock.today), limit: 5 });
}

/** Which meals of the day are still ahead at this local hour. */
function slotsAhead(hour: number): MealSlot[] {
  const ahead: MealSlot[] = [];
  if (hour < 11) ahead.push("breakfast");
  if (hour < 15) ahead.push("lunch");
  if (hour < 21) ahead.push("dinner");
  ahead.push("snack");
  return ahead;
}

/**
 * FORM Pro: meals for the rest of today from what's left of today's targets (target minus what's
 * already logged), respecting allergies, diet, dislikes, cooking time, budget and saved recipes.
 * Never plans the day below the safe minimum; suggestions only — nothing logged or replaced.
 */
export function restOfToday(ctx: AppContext, userId: string, clock: UserClock) {
  const { db } = ctx;
  const t = targetOn(db, userId, clock.today);
  if (!t) throw new HttpError(422, "targets_required", "Add your body details in Profile first, so suggestions fit your energy needs safely.");
  const eaten = db.prepare("SELECT COALESCE(SUM(kcal), 0) AS kcal, COALESCE(SUM(protein_g), 0) AS p, COALESCE(SUM(carbs_g), 0) AS c, COALESCE(SUM(fat_g), 0) AS f FROM food_logs WHERE user_id = ? AND local_date = ?").get(userId, clock.today) as { kcal: number; p: number; c: number; f: number };
  const remaining = { kcal: t.targetKcal - eaten.kcal, proteinG: Math.max(0, t.proteinG - eaten.p), carbsG: Math.max(0, t.carbsG - eaten.c), fatG: Math.max(0, t.fatG - eaten.f) };
  const slots = slotsAhead(clock.hour);
  if (remaining.kcal < 150) {
    return { date: clock.today, eaten: presentMacros({ kcal: eaten.kcal, proteinG: eaten.p, carbsG: eaten.c, fatG: eaten.f }), remaining: presentMacros({ ...remaining, kcal: Math.max(0, remaining.kcal) }), meals: [], warnings: [], done: true };
  }
  const floorLeft = Math.max(0, t.safeFloorKcal - eaten.kcal);
  let generated;
  try {
    generated = generateMealPlan({
      dates: [clock.today],
      targets: { ...remaining, safeFloorKcal: Math.min(floorLeft, remaining.kcal) },
      personalization: personalization(db, userId, clock.today),
      recipes: RECIPE_LIBRARY,
      seed: `${userId}|${clock.today}|rest`,
      slots,
      favorites: savedIds(db, userId),
    });
  } catch (e) {
    if (e instanceof PlanGenerationError) throw new HttpError(422, e.code, e.message);
    throw e;
  }
  const day = generated.days[0]!;
  return {
    date: clock.today,
    eaten: presentMacros({ kcal: eaten.kcal, proteinG: eaten.p, carbsG: eaten.c, fatG: eaten.f }),
    remaining: presentMacros(remaining),
    meals: day.meals.map((m) => ({ slot: m.slot, recipeId: m.recipeId, title: RECIPE_LIBRARY.find((r) => r.id === m.recipeId)?.title ?? m.recipeId, servings: m.servings, nutrients: presentMacros(m.nutrients) })),
    warnings: generated.warnings,
    done: false,
  };
}
